### Ratio > 2:1 image
POST {{param.vision.Normalize}}
content-type: application/json

< ImageNormalization.PNG.3.json

### Small image
POST {{param.vision.Normalize}}
content-type: application/json

< ImageNormalization.PNG.4.json

### Small b&w image
POST {{param.vision.Normalize}}
content-type: application/json

< ImageNormalization.PNG.5.json
