###
POST {{param.language.LanguageDetection}}
content-type: application/json;charset=utf-8
defaultCountryHint: us
type: big

< LanguageDetection.1.json

###
POST {{param.language.LanguageDetection}}
content-type: application/json;charset=utf-8

< LanguageDetection.2.json

###
POST {{param.language.LanguageDetection}}
content-type: application/json;charset=utf-8

< LanguageDetection.3.json

###
POST {{param.language.LanguageDetection}}
content-type: application/json;charset=utf-8

< LanguageDetection.4.json
