apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-app
  labels:
    # any Pods with matching labels are included in this Daemon Set
    app: kubernetes-series
    tier: monitor
spec:
  selector:
    # Pods will match with the following labels
    matchLabels:
      name: language-app
  template:
    metadata:
      labels:
        name: language-app
    spec:
      containers:
      - name: language-app
        image: {{param.acr}}/microsoft/language:latest
        ports:
        - containerPort: 80
        env:
        - name: WEBSITE_HOSTNAME
          value: "{{param.kubernetesHost}}"
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "{{param.storageConnectionString}}"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "{{param.appInsightsServiceKey}}"
        - name: AzureWebJobsStorage
          value: "{{param.techStorageConnectionString}}"
        - name: BLOB_CONNECT_STRING
          value: "{{param.storageConnectionString}}"
        - name: TEXT_ANALYTICS_ENDPOINT
          value: "https://{{param.cogSvcLanguage}}.cognitiveservices.azure.com"
        - name: TEXT_ANALYTICS_KEY
          value: "{{param.cogSvcLanguageKey}}"
        - name: TEXT_TRANSLATION_ENDPOINT
          value: "https://{{param.cogSvcTranslate}}.cognitiveservices.azure.com/translator/text/v3.0"
        - name: TEXT_TRANSLATION_KEY
          value: "{{param.cogSvcTranslateKey}}"
        - name: TEXT_TRANSLATION_LOCATION
          value: "{{config.location}}"
        - name: MODEL_SIZE
          value: "lg"
        - name: StorageAccountName
          value: "{{param.dataStorageAccountName}}"
        - name: StorageKey
          value: "{{param.storageAccountKey}}"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 4000m
            memory: 16Gi
      nodeSelector:
        agentpool: poolcogs
--- 
apiVersion: v1
kind: Service
metadata:
  name: language-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: language-app
