### See https://docs.microsoft.com/en-us/rest/api/searchservice/suggestions#request-body

### Suggestions Test 1
POST  https://{{param.searchServiceName}}.search.windows.net/indexes/{{param.indexName}}/docs/suggest?api-version={{config.searchVersion}}
content-type: application/json;charset=utf-8
api-key : {{param.searchServiceQueryKey}}

{  
    "search": "eu",  
    "top": 5,  
    "suggesterName": "suggester1"  
} 

