###
POST {{param.language.KeyPhrasesExtraction}}
Content-Type: application/json
minimumPrecision: 0.2
defaultLanguageCode: en
type: small

< KeyPhrases.1.json

###
POST {{param.language.KeyPhrasesExtraction}}
Content-Type: application/json

< KeyPhrases.2.json

