###
POST {{param.language.KeyPhrasesExtraction}}
content-type: application/json;charset=utf-8
minimumPrecision: 0.2
defaultLanguageCode: en
type: small

< KeyPhrases.1.json

###
POST {{param.language.KeyPhrasesExtraction}}
content-type: application/json;charset=utf-8

< KeyPhrases.2.json

