### Trasnslate 
POST  https://api-eur.cognitive.microsofttranslator.com/translate?api-version=3.0&to={{config.searchDefaultToLanguageCode}}&suggestedFrom={{config.searchDefaultFromLanguageCode}}
content-type: application/json;charset=utf-8
Ocp-Apim-Subscription-Key : {{param.cogSvcTranslateKey}}
Ocp-Apim-Subscription-Region: {{config.location}}

[
    {"Text":"Hello, what is your name?"}
]