apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{config.name}}-healthz
  namespace: dstoolkit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /language/status
    kubernetes.io/ingress.allow-http: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - services.contoso.net
  rules:
  - host: services.contoso.net
    http:
      paths:
      - path: /healthz
        pathType: Prefix
        backend:
          service:
            name: language-service
            port:
              number: 80
