POST http://localhost:7071/imgext/DurableImageExtractionSkill_HttpStart
content-type: application/json;charset=utf-8

{
    "values": [
        {
            "recordId": "1",
            "data": {
                "document_index_key": "aHR0cHM6Ly9rbWRlbW9kYXRhLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvU2FtcGxlRGF0YTEwLVdpbmQvV2luZCBFbmVyZ3kgMTAxLnBkZg",
                "document_id": "aHR0cHM6Ly9rbWRlbW9kYXRhLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvU2FtcGxlRGF0YTEwLVdpbmQvV2luZCBFbmVyZ3kgMTAxLnBkZg",
                "document_filename":"Test.pptx",
                "document_url":"https://kmsolacdata.blob.core.windows.net/images/documents/emails/TestEmail.msg/Test.pptx"
            }
        }
    ]
}
###
POST http://localhost:7071/imgext/ImageExtractionSkill
content-type: application/json;charset=utf-8

{
    "values": [
        {
            "recordId": "1",
            "data": {
                "document_index_key": "aHR0cHM6Ly9rbWRlbW9kYXRhLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvU2FtcGxlRGF0YTEwLVdpbmQvV2luZCBFbmVyZ3kgMTAxLnBkZg",
                "document_id": "aHR0cHM6Ly9rbWRlbW9kYXRhLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvU2FtcGxlRGF0YTEwLVdpbmQvV2luZCBFbmVyZ3kgMTAxLnBkZg",
                "document_filename":"Test.pptx",
                "document_url":"https://kmsolacdata.blob.core.windows.net/images/documents/emails/TestEmail.msg/Test.pptx"
            }
        }
    ]
}
