apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: entities-app
  labels:
    # any Pods with matching labels are included in this Daemon Set
    app: kubernetes-series
    tier: monitor
spec:
  selector:
    # Pods will match with the following labels
    matchLabels:
      name: entities-app
  template:
    metadata:
      labels:
        name: entities-app
    spec:
      containers:
      - name: entities-app
        image: {{param.acr}}/microsoft/entities:latest
        ports:
        - containerPort: 80
        env:
        - name: WEBSITE_HOSTNAME
          value: "{{param.kubernetesHost}}"
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "{{param.storageConnectionString}}"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "{{param.appInsightsServiceKey}}"
        - name: AzureWebJobsStorage
          value: "{{param.techStorageConnectionString}}"
        - name: NoisePhrases
          value: "Document Id,last updated when,Labels,Parentlabels,Title Tags,Attachment Tags,[image: ],<,>,Please document here or link to the file.,[image:,last updated by"
        - name: stopwords
          value: "image,internet,E-Mail,Fax,freundlichen Grüßen,Title Tags,Attachment Tags,pptx,Document Id,Parentlabels,Table of content,table of contents"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
      nodeSelector:
        agentpool: poolskills

--- 
apiVersion: v1
kind: Service
metadata:
  name: entities-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: entities-app
