apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tika-app
  labels:
    # any Pods with matching labels are included in this Daemon Set
    app: kubernetes-series
    tier: monitor
spec:
  selector:
    # Pods will match with the following labels
    matchLabels:
      name: tika-app
  template:
    metadata:
      labels:
        name: tika-app
    spec:
      containers:
      - name: tika-app
        image: {{param.acr}}/microsoft/tika:latest
        ports:
        - containerPort: 9998
        env:
        - name: WEBSITE_HOSTNAME
          value: "{{param.kubernetesHost}}"
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "{{param.storageConnectionString}}"
        resources:
          requests:
            cpu: 2000m
            memory: 4Gi
          limits:
            cpu: 15500m
            memory: 60Gi
      nodeSelector:
        agentpool: pooltika

--- 
apiVersion: v1
kind: Service
metadata:
  name: tika-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 9998
  selector:
    name: tika-app
