POST {{param.ocrlayout.azureocrlayout}}
content-type: application/json

{
    "values": [
        {
            "recordId": "1",
            "data": {
                "width": 1284,
                "height": 1655,
                "layoutText":
{
	"language": "en",
	"text": "upme\nUnidad de Planeación Minero Energética\nCadena del\nPetróleo\nMinMinas\nPROSPERIDAD\nMinisterio de Minas y Energía\nPARA TODOS",
	"lines": [
		{
			"boundingBox": [
				{
					"x": 113,
					"y": 353
				},
				{
					"x": 420,
					"y": 343
				},
				{
					"x": 424,
					"y": 447
				},
				{
					"x": 119,
					"y": 465
				}
			],
			"text": "upme"
		},
		{
			"boundingBox": [
				{
					"x": 192,
					"y": 456
				},
				{
					"x": 417,
					"y": 457
				},
				{
					"x": 417,
					"y": 474
				},
				{
					"x": 192,
					"y": 472
				}
			],
			"text": "Unidad de Planeación Minero Energética"
		},
		{
			"boundingBox": [
				{
					"x": 505,
					"y": 584
				},
				{
					"x": 976,
					"y": 584
				},
				{
					"x": 976,
					"y": 657
				},
				{
					"x": 505,
					"y": 657
				}
			],
			"text": "Cadena del"
		},
		{
			"boundingBox": [
				{
					"x": 498,
					"y": 676
				},
				{
					"x": 1185,
					"y": 679
				},
				{
					"x": 1184,
					"y": 799
				},
				{
					"x": 498,
					"y": 797
				}
			],
			"text": "Petróleo"
		},
		{
			"boundingBox": [
				{
					"x": 742,
					"y": 1449
				},
				{
					"x": 821,
					"y": 1449
				},
				{
					"x": 821,
					"y": 1467
				},
				{
					"x": 742,
					"y": 1466
				}
			],
			"text": "MinMinas"
		},
		{
			"boundingBox": [
				{
					"x": 984,
					"y": 1434
				},
				{
					"x": 1211,
					"y": 1435
				},
				{
					"x": 1211,
					"y": 1465
				},
				{
					"x": 984,
					"y": 1464
				}
			],
			"text": "PROSPERIDAD"
		},
		{
			"boundingBox": [
				{
					"x": 738,
					"y": 1468
				},
				{
					"x": 883,
					"y": 1468
				},
				{
					"x": 883,
					"y": 1483
				},
				{
					"x": 738,
					"y": 1483
				}
			],
			"text": "Ministerio de Minas y Energía"
		},
		{
			"boundingBox": [
				{
					"x": 963,
					"y": 1460
				},
				{
					"x": 1212,
					"y": 1460
				},
				{
					"x": 1212,
					"y": 1494
				},
				{
					"x": 963,
					"y": 1495
				}
			],
			"text": "PARA TODOS"
		}
	],
	"words": [
		{
			"boundingBox": [
				{
					"x": 180,
					"y": 350
				},
				{
					"x": 419,
					"y": 343
				},
				{
					"x": 424,
					"y": 451
				},
				{
					"x": 185,
					"y": 462
				}
			],
			"text": "upme"
		},
		{
			"boundingBox": [
				{
					"x": 197,
					"y": 456
				},
				{
					"x": 236,
					"y": 457
				},
				{
					"x": 235,
					"y": 472
				},
				{
					"x": 197,
					"y": 473
				}
			],
			"text": "Unidad"
		},
		{
			"boundingBox": [
				{
					"x": 239,
					"y": 457
				},
				{
					"x": 253,
					"y": 457
				},
				{
					"x": 252,
					"y": 472
				},
				{
					"x": 238,
					"y": 472
				}
			],
			"text": "de"
		},
		{
			"boundingBox": [
				{
					"x": 256,
					"y": 457
				},
				{
					"x": 315,
					"y": 457
				},
				{
					"x": 315,
					"y": 472
				},
				{
					"x": 256,
					"y": 472
				}
			],
			"text": "Planeación"
		},
		{
			"boundingBox": [
				{
					"x": 319,
					"y": 457
				},
				{
					"x": 356,
					"y": 458
				},
				{
					"x": 355,
					"y": 472
				},
				{
					"x": 318,
					"y": 472
				}
			],
			"text": "Minero"
		},
		{
			"boundingBox": [
				{
					"x": 359,
					"y": 458
				},
				{
					"x": 418,
					"y": 458
				},
				{
					"x": 418,
					"y": 474
				},
				{
					"x": 358,
					"y": 472
				}
			],
			"text": "Energética"
		},
		{
			"boundingBox": [
				{
					"x": 505,
					"y": 586
				},
				{
					"x": 816,
					"y": 585
				},
				{
					"x": 816,
					"y": 658
				},
				{
					"x": 506,
					"y": 658
				}
			],
			"text": "Cadena"
		},
		{
			"boundingBox": [
				{
					"x": 830,
					"y": 585
				},
				{
					"x": 976,
					"y": 585
				},
				{
					"x": 975,
					"y": 658
				},
				{
					"x": 830,
					"y": 658
				}
			],
			"text": "del"
		},
		{
			"boundingBox": [
				{
					"x": 499,
					"y": 677
				},
				{
					"x": 1182,
					"y": 684
				},
				{
					"x": 1182,
					"y": 799
				},
				{
					"x": 498,
					"y": 799
				}
			],
			"text": "Petróleo"
		},
		{
			"boundingBox": [
				{
					"x": 744,
					"y": 1449
				},
				{
					"x": 821,
					"y": 1450
				},
				{
					"x": 821,
					"y": 1467
				},
				{
					"x": 744,
					"y": 1467
				}
			],
			"text": "MinMinas"
		},
		{
			"boundingBox": [
				{
					"x": 986,
					"y": 1435
				},
				{
					"x": 1211,
					"y": 1436
				},
				{
					"x": 1209,
					"y": 1465
				},
				{
					"x": 984,
					"y": 1465
				}
			],
			"text": "PROSPERIDAD"
		},
		{
			"boundingBox": [
				{
					"x": 743,
					"y": 1469
				},
				{
					"x": 788,
					"y": 1468
				},
				{
					"x": 787,
					"y": 1484
				},
				{
					"x": 743,
					"y": 1484
				}
			],
			"text": "Ministerio"
		},
		{
			"boundingBox": [
				{
					"x": 791,
					"y": 1468
				},
				{
					"x": 802,
					"y": 1468
				},
				{
					"x": 802,
					"y": 1484
				},
				{
					"x": 790,
					"y": 1484
				}
			],
			"text": "de"
		},
		{
			"boundingBox": [
				{
					"x": 805,
					"y": 1468
				},
				{
					"x": 834,
					"y": 1469
				},
				{
					"x": 834,
					"y": 1484
				},
				{
					"x": 805,
					"y": 1484
				}
			],
			"text": "Minas"
		},
		{
			"boundingBox": [
				{
					"x": 837,
					"y": 1469
				},
				{
					"x": 842,
					"y": 1469
				},
				{
					"x": 842,
					"y": 1484
				},
				{
					"x": 837,
					"y": 1484
				}
			],
			"text": "y"
		},
		{
			"boundingBox": [
				{
					"x": 845,
					"y": 1469
				},
				{
					"x": 883,
					"y": 1469
				},
				{
					"x": 883,
					"y": 1484
				},
				{
					"x": 845,
					"y": 1484
				}
			],
			"text": "Energía"
		},
		{
			"boundingBox": [
				{
					"x": 987,
					"y": 1461
				},
				{
					"x": 1080,
					"y": 1463
				},
				{
					"x": 1079,
					"y": 1496
				},
				{
					"x": 986,
					"y": 1495
				}
			],
			"text": "PARA"
		},
		{
			"boundingBox": [
				{
					"x": 1087,
					"y": 1463
				},
				{
					"x": 1212,
					"y": 1462
				},
				{
					"x": 1211,
					"y": 1494
				},
				{
					"x": 1086,
					"y": 1496
				}
			],
			"text": "TODOS"
		}
	]
}
            }
        }
    ]
}


###
POST {{param.ocrlayout.azureocrlayout}}
content-type: application/json

{
    "values": [
        {
            "recordId": "1",
            "data": {
                "width": 816,
                "height": 352,
                "layoutText":
{
	"language": "en",
	"text": "NREL",
	"lines": [
		{
			"boundingBox": [
				{
					"x": 104,
					"y": 42
				},
				{
					"x": 176,
					"y": 42
				},
				{
					"x": 176,
					"y": 66
				},
				{
					"x": 104,
					"y": 66
				}
			],
			"text": "NREL"
		}
	],
	"words": [
		{
			"boundingBox": [
				{
					"x": 105,
					"y": 43
				},
				{
					"x": 176,
					"y": 43
				},
				{
					"x": 174,
					"y": 67
				},
				{
					"x": 105,
					"y": 67
				}
			],
			"text": "NREL"
		}
	]
}
            }
        }
    ]
}
